-- MySQL Script generated by MySQL Workbench
-- 02/02/16 12:59:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_teste_noatel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_teste_noatel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_teste_noatel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_teste_noatel` ;

-- -----------------------------------------------------
-- Table `bd_teste_noatel`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_teste_noatel`.`contacts` (
  `idcontacts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `surname` VARCHAR(100) NULL,
  `phone` VARCHAR(22) NULL,
  PRIMARY KEY (`idcontacts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_teste_noatel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_teste_noatel`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
